---
title: 'DATA 607:  HTML, XML, JSON; Week 7'
author: "Walt Wells, Fall 2016"
output:
  html_document:
    theme: lumen
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

Our goal in this lesson is to create a list of books stored in an HTML table, an XML file, and a JSON file and use R to read and parse the files and store in 3 data frames.   We should then review the resulting data frames and note any differences.  

# Environment Prep
```{r, warning=FALSE, message=FALSE}
if (!require('rvest')) install.packages('rvest')
if (!require('XML')) install.packages('XML')
if (!require('jsonlite')) install.packages('jsonlite')
```

# HTML Table
```{r}
h <- read_html("books.html") 
h.df <- data.frame(html_table(h))
knitr::kable(h.df)
```

# XML
```{r}
x <- xmlParse("books.xml")
x.df <- xmlToDataFrame(x)
knitr::kable(x.df)
```

# JSON
```{r}
j <- fromJSON("books.json")
j.df <- do.call("rbind", lapply(j, data.frame, stringsAsFactors=FALSE))
rownames(j.df) <- NULL
knitr::kable(j.df)
```

# Testing Similarity
