---
title: "AutomatedDataCollection_C1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### World Heritage Sites in Danger

From *Automated Data Collection with R:  A Practical Guide to Web Scrapting and Text Mining*, Munzert, Rubba, Meisner, Nyhuis; 

```{r, warning=FALSE}
library(stringr)
library(XML)
library(maps)
if (!require("DT")) install.packages('DT')

## load data
heritage_parsed <- htmlParse("http://www.r-datacollection.com/materials/ch-1-introduction/worldheritagedanger.htm", encoding = "UTF-8")
tables <- readHTMLTable(heritage_parsed, stringAsFactors=FALSE)

## grab 2nd table and subset
danger_table <- tables[[2]]
names(danger_table)
danger_table <- danger_table[, c(1,3,4,6,7)]
colnames(danger_table) <- c("name", "locn", "crit", "yins", "yend")

#### CLEANING
danger_table$crit <- ifelse(str_detect(danger_table$crit, "Natural") ==
                                TRUE, "nat", "cult")
danger_table$yins <- as.numeric(format(danger_table$yins, format="%Y"))
yend_clean <- unlist(str_extract_all(danger_table$yend, "[[:digit:]]{4}$"))
danger_table$yend <- as.numeric(format(yend_clean, format="%Y"))

# get countries
reg <- "[[:alpha:] ]+(?=[[:digit:]])"
country <- str_extract(danger_table$locn, regex(reg)) # use forward assertion in Perl regular expression
country[29] <- "Côte d'Ivoire / Guinea"
country[32] <- ""
danger_table$country <- country

# get coordinates
reg_y <- "[/][ -]*[[:digit:]]*[.]*[[:digit:]]*[;]"
reg_x <- "[;][ -]*[[:digit:]]*[.]*[[:digit:]]*"
y_coords <- str_extract(danger_table$locn, reg_y)
y_coords <- round(as.numeric(str_sub(y_coords, 3, -2)), 2)
danger_table$y_coords <- y_coords
x_coords <- str_extract(danger_table$locn, reg_x)
x_coords <- round(as.numeric(str_sub(x_coords, 3, -1)), 2)
danger_table$x_coords <- x_coords
danger_table$locn <- NULL

datatable(danger_table, options = list(pageLength = 5))

### plot
pch <- ifelse(danger_table$crit == "nat", 19, 2)
map("world", col = "darkgrey", lwd = .5, mar = c(0.1,0.1,0.1,0.1))
points(danger_table$x_coords, danger_table$y_coords, pch = pch, col="red", cex = .8)
box()

# table heritage criteria
table(danger_table$crit)

hist(danger_table$yend, freq=TRUE, xlab="Year when site was put on the list of endangered sites", main = "")

duration <- danger_table$yend - danger_table$yins
hist(duration, freq=TRUE, xlab="Years it took to become an endangered site")

```